name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Runs daily
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: <jjoseph-anderson>
          template: classic
          base: header, repositories
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_sort: stars
